# Generated by Django 4.1.5 on 2023-01-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(max_length=50, null=True)),
                ('tone', models.CharField(max_length=50)),
                ('storyPrompt', models.TextField()),
                ('imagePrompt', models.TextField()),
                ('isPrivate', models.BooleanField()),
                ('storyResult', models.TextField(default='')),
                ('imageUrl', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Storyboards',
            },
        ),
    ]
